package com.motorinsurance.shared.storage;

/**
 * What {@link Storage} hands back once bytes are safely on disk (Story 10.1,
 * Epic 10 technical decisions): everything a caller needs to persist a
 * reference to the file, and nothing about who may see it - that rule
 * belongs to the claim (Story 10.4), not to the byte-level concern.
 *
 * <p>{@code storageKey} is generated by the adapter, never by a client: it
 * is the only string that ever reaches a filesystem path, which is what
 * makes traversal sequences and executable extensions unrepresentable by
 * construction. {@code displayFilename} is the client-supplied name kept
 * purely so a client recognises its own photo in a list; it is never
 * resolved against the storage directory.
 *
 * <p>{@code contentType} is the type the caller vouched for - for an upload
 * that is {@code AttachmentValidator}'s sniffed result, never the
 * {@code Content-Type} header the client sent. {@code sha256Hex} is computed
 * over the exact bytes written, so a later read can be proven byte-identical
 * to what was accepted.
 *
 * <p>Defined here rather than in {@code claim} so this story ships without a
 * table: Story 10.2's {@code attachments} row is written from exactly these
 * five values.
 */
public record StoredFile(
        String storageKey, String contentType, long sizeBytes, String sha256Hex, String displayFilename) {
}
